const { JSDOM } = require('jsdom')
const { loadPanel, installDom } = require('./harness')
const dom = new JSDOM('<!doctype html><body><div id=tab></div></body>', { pretendToBeVisual: true })
installDom(dom)
const { AITerminalPanel } = loadPanel()
const ok = (name, cond, extra = '') => console.log(`${cond ? 'PASS' : 'FAIL'}  ${name}${extra !== '' ? '  | ' + extra : ''}`)
const sleep = ms => new Promise(r => setTimeout(r, ms))
const host = document.getElementById('tab'); const sub = { subscribe: () => ({ unsubscribe () {} }) }
let opened = null, h = null
const auth = { statusChanged$: sub, cliUpdated$: sub, isCliUpdating: () => false, getCliUpdateStatus: () => undefined, getKnownCliVersion: () => undefined, getSelectedProvider: () => 'claude', getSelectedModel: () => 'opus', getAvailableModels: async () => ['opus'], getClaudeModelStatus: () => undefined, publishStatus () {} }
const p = new AITerminalPanel({ element: { nativeElement: host }, title: 'T', sendInput () {}, frontend: { focus () {} }, configure () {} }, auth, { run (r, x) { h = x; return { cancel () {} } }, getClaudeRunSettings: () => ({ requested: 'plan', mode: 'plan' }) }, { store: { aiTerminal: { maxSessionOutputLines: 1000, savedSenderCommands: [] } }, save: async () => {}, changed$: sub }, { showMessageBox: async () => ({ response: 0 }), openExternal: u => { opened = u }, setClipboard () {} })
host.append(p.element, p.senderElement); p.applyProviderStatus({ provider: 'claude', state: 'logged-in', label: 'ok' })
const { renderMarkdown } = require('./harness').load('markdown')
const md = t => renderMarkdown(t, url => { opened = url })
let r = md('- **`root`**: superuser\n- **`~`**: home')
ok('bold wrapping code renders code inside strong (no backticks)', r.querySelector('li strong code') && r.querySelector('li strong code').textContent === 'root' && !r.textContent.includes('`'), r.innerHTML.slice(0, 80))
r = md('Use `phy0_ap0` and snake_case_name, not _this_ or *that*.')
ok('underscores in identifiers stay literal; _x_ and *x* become em', r.textContent.includes('snake_case_name') && [...r.querySelectorAll('em')].map(e => e.textContent).join(',') === 'this,that', r.innerHTML)
r = md('- a\n  - a1\n  - a2\n- b\n1. one\n2. two')
ok('nested list', r.querySelector('ul > li > ul') && r.querySelectorAll('ul > li > ul > li').length === 2 && r.querySelector('ol') && r.querySelectorAll('ol li').length === 2)
r = md('> quoted **text**\n> line two\n\nafter\n\n---\n\nend')
ok('blockquote + hr', r.querySelector('blockquote strong') && r.querySelector('blockquote').textContent.includes('line two') && r.querySelector('hr'))
r = md('See [docs](https://example.com/x) and [bad](javascript:alert(1)).')
const links = r.querySelectorAll('a.ai-md-link'); links[0].click(); const first = opened; opened = null; links[1] && links[1].click()
ok('links open externally; non-http blocked', first === 'https://example.com/x' && opened === null, `${links.length} links`)
r = md('```sh\n**not bold** `x`\n```')
ok('code block content is literal', r.querySelector('pre.ai-md-code').textContent === '**not bold** `x`')
r = md('| a | b |\n|---|---|\n| `c` | **d** |')
ok('table cells render inline md, wrapped for scrolling', r.querySelector('.ai-md-table-wrap table td code') && r.querySelector('td strong'))
r = md('<img src=x onerror=alert(1)> **ok**')
ok('raw HTML is not interpreted (text only)', !r.querySelector('img') && r.textContent.includes('<img'))
;(async () => {
  p.appendOutput('x\r\n'); await p.analyze()
  h.output('The **radio** is'); await sleep(260)
  const card = p.chatHistory.querySelector('.ai-chat-message')
  ok('live render while streaming (no raw ** visible)', card.querySelector('.ai-markdown strong') && card.querySelector('pre.ai-analysis').hidden)
  h.output(' up.\n\n## Suggested commands\n```sh\nwifi status\n```\n'); h.done(0)
  ok('final render replaces live view, single answer body', card.querySelectorAll('.ai-markdown').length === 1 && card.querySelector('.ai-suggested'))
  const openBtn = [...card.querySelectorAll('.ai-answer-actions button')].find(b => b.textContent === 'Open')
  openBtn.click()
  const ov = document.querySelector('.ai-viewer-overlay')
  ok('Open shows large viewer with rendered answer', ov && ov.querySelector('.ai-viewer-body strong').textContent === 'radio' && ov.querySelector('.ai-viewer-title').textContent.startsWith('Answer'))
  ov.dispatchEvent(new window.KeyboardEvent('keydown', { key: 'Escape', bubbles: true }))
  ok('Esc closes viewer', !document.querySelector('.ai-viewer-overlay'))
})()
