/// <reference types="node" />
import { Observable } from 'rxjs';
import { ConfigService, PlatformService } from 'tabby-core';
import { AIProviderID, AIProviderStatus } from '../providers';
export declare class AIProviderAuthService {
    private config;
    private platform;
    private statusChecks;
    private statusChanged;
    private modelChecks;
    get statusChanged$(): Observable<AIProviderStatus>;
    constructor(config: ConfigService, platform: PlatformService);
    getSelectedProvider(): AIProviderID;
    setSelectedProvider(provider: AIProviderID): Promise<AIProviderStatus>;
    getSelectedModel(): string;
    setSelectedModel(model: string): Promise<void>;
    getAvailableModels(providerID?: AIProviderID, force?: boolean): Promise<string[]>;
    checkSelectedProviderStatus(): Promise<AIProviderStatus>;
    checkProviderStatus(providerID: AIProviderID): Promise<AIProviderStatus>;
    publishStatus(status: AIProviderStatus): void;
    startLogin(providerID?: AIProviderID): Promise<void>;
    confirmCloseForEnvironmentRefresh(providerID?: AIProviderID): Promise<boolean>;
    confirmAndStartLogout(providerID?: AIProviderID): Promise<boolean>;
    confirmResetSession(): Promise<boolean>;
    private checkProviderStatusNow;
    private execProviderCommand;
    private isProviderCommandAvailableAfterEnvironmentRefresh;
    private isProviderCommandAvailable;
    private resolveProviderExecutable;
    private findUsableProviderExecutable;
    private isUsableProviderExecutable;
    buildProviderCommandInvocation(command: string, args: string[]): {
        command: string;
        args: string[];
        env: NodeJS.ProcessEnv;
    };
    private fetchAvailableModels;
    private extractCodexModelCatalog;
    private mergeModelOptions;
    private resolveCommandResult;
    private extractAccountLabel;
    private openExternalTerminal;
    private buildProviderLoginCommand;
    private withWindowsUTF8CodePage;
    private encodePowerShellCommand;
    private getLinuxTerminalCandidates;
    private wrapInUserLoginShell;
    private getUserLoginShell;
    private getAugmentedCommandEnv;
    private getWindowsRegistryCommandEnv;
    private readWindowsRegistryPath;
    private expandWindowsEnvironmentVariables;
    private getWindowsPathEnvKey;
    private commandLine;
    private spawnDetached;
}
