/// <reference types="node" />
/// <reference types="node" />
import { BaseTerminalTabComponent } from 'tabby-terminal';
import { ConfigService, PlatformService } from 'tabby-core';
import { AIProviderAuthService } from './services/aiProviderAuth.service';
import { AIProviderRunnerService } from './services/aiProviderRunner.service';
export declare class AITerminalPanel {
    private tab;
    private config;
    private platform;
    readonly element: HTMLElement;
    readonly senderElement: HTMLElement;
    private providerAuth;
    private providerRunner;
    private header;
    private headerControls;
    private referenceFolderRow;
    private signedInIdentity;
    private providerSelect;
    private modelSelect;
    private statusLine;
    private loginOnly;
    private content;
    private headerLogoutButton;
    private loginOnlyLoginButton;
    private clearLatestButton;
    private resetSessionButton;
    private referenceFolderButton;
    private clearReferenceFolderButton;
    private referenceFolderPathElement;
    private analyzeButton;
    private cancelButton;
    private runningIndicator;
    private question;
    private chatBody;
    private chatStack;
    private chatViewport;
    private chatHistory;
    private latestOutputDetails;
    private latestOutputSummary;
    private latestOutputMeta;
    private output;
    private currentAnalysis;
    private draft;
    private recentOutputLines;
    private pendingOutput;
    private currentInputLine;
    private skipNextEmptyInputOutputLine;
    private visible;
    private signedIn;
    private lastPanelVisible;
    private lastSenderVisible;
    private chatAutoScroll;
    private pendingLoginRefreshes;
    private aiSessionID;
    private referenceFolder;
    private lastProviderStatus;
    private lastFocusRefreshAt;
    private environmentRefreshPromptShown;
    private statusSubscription;
    private runHandle;
    private modelRefreshPromise;
    private layoutObserver;
    private layoutFrame;
    constructor(tab: BaseTerminalTabComponent<any>, providerAuth: AIProviderAuthService, providerRunner: AIProviderRunnerService, config: ConfigService, platform: PlatformService);
    destroy(): void;
    appendOutput(data: string): void;
    handleInput(data: string | Buffer): void;
    toggle(): void;
    private analyze;
    private cancelAnalyze;
    private appendAnalysis;
    private syncDraftFromAnalysisCodeBlock;
    private extractLastCodeBlock;
    private setRunning;
    private render;
    private applyFontSize;
    private getFontSize;
    private setAISessionID;
    private refreshAfterFocus;
    private refreshProviderStatus;
    private setProvider;
    private login;
    private logout;
    private applyProviderStatus;
    private getLoginButtonLabel;
    private maybePromptForEnvironmentRefresh;
    private renderProviderIdentity;
    private shouldRefreshAfterFocus;
    private refreshModelOptions;
    private refreshModelOptionsNow;
    private modelOption;
    private appendSentChatMessage;
    private sendDraftLine;
    private sendDraftAll;
    private section;
    private collapsibleOutput;
    private observeDynamicLayout;
    private scheduleDynamicLayoutUpdate;
    private updateDynamicLayout;
    private toPixels;
    private scrollChatToBottom;
    private isChatScrolledToBottom;
    private clearLatestSessionOutput;
    private resetSession;
    private selectReferenceFolder;
    private clearReferenceFolder;
    private confirmSessionResetForReferenceFolderChange;
    private resetAIChatSession;
    private renderReferenceFolder;
    private formatReferenceFolderPath;
    private updateLatestOutputFromEditor;
    private requestTerminalRefit;
    private scrollLatestOutputToBottom;
    private isLatestOutputScrolledToBottom;
    private guardTerminalEvents;
    private focusEventSurface;
    private textarea;
    private button;
    private createRunningIndicator;
    private stripAnsi;
    private trimRecentOutput;
    private getSessionOutputLimit;
    private getRecentOutputText;
    private redactSensitiveText;
    private countOutputLines;
    private formatLineCount;
    private getDisplayOutputLines;
    private handleTerminalSubmit;
    private shouldIgnoreEmptyEnterPrompts;
    private trackTerminalInput;
    private appendOutputLine;
    private flushPendingOutput;
    private normalizeOutputLine;
    private skipEscapeSequence;
    private applyInputCharacter;
}
